# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_-N5jZ_uXydIGbEGElocptEa69IjHMPE

#Elaborando gráficos: histograma, dispersão, combinações e boxplot com py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io

from google.colab import files
uploaded = files.upload()

arvores = pd.read_csv("trees.csv") #Chamando pelo nome o arquivo: dataset
arvores.head() #ler

arvores.shape #contando

"""#Histograma usando a biblioteca NP

Agora, para gerar histograma com a biblioteca NP. Com apenas a segunda coluna "height" (usando iloc para definir a coluna, lembrando que py começa contando com 0), e com 6 divisões de barras (bins)/ou eixos. A variável representando height é H
"""

h = np.histogram(arvores.iloc[:,1], bins=6)
h

"""Após definir, gera o Histograma com a Biblioteca plt"""

plt.hist(arvores.iloc[:,1], bins=6)
plt.title('Arvore')
plt.ylabel('Frequência')
plt.xlabel('Altura')

"""#Dispersão com plt

"""

arvores.head()

"""Cor de fundo "facecolors"
marker é marcadores em que escolhemos estrela
Volume é o outro eixo, apos o eixo Girth
"""

plt.scatter(arvores.Girth, arvores.Volume, color = "purple", facecolors = "none", marker = "*")
plt.title('Arvore')
plt.xlabel('Volume')
plt.ylabel('Circunferência')

"""Sem marcadorres"""

plt.scatter(arvores.Girth, arvores.Volume, color = "purple", facecolors = "none")
plt.title('Arvore')
plt.xlabel('Volume')
plt.ylabel('Circunferência')

"""Linha"""

plt.plot(arvores.Girth, arvores.Volume)
plt.title('Arvore')
plt.xlabel('Volume')
plt.ylabel('Circunferência')

"""#Gráficos coletivos"""

plt.scatter(arvores.Girth, arvores.Volume)

"""Relação clara"""

plt.scatter(arvores.Girth, arvores.Height)

plt.scatter(arvores.Height, arvores.Volume, marker="*")

plt.hist(arvores.Volume)

"""Para criar um gráfico único

"""

plt.figure(1) #primeiro cria a figura
plt.subplot(2,2,1)
plt.scatter(arvores.Girth, arvores.Volume)
plt.subplot(2,2,2)
plt.scatter(arvores.Girth, arvores.Height)
plt.subplot(2,2,3)
plt.scatter(arvores.Height, arvores.Volume, marker="*")
plt.subplot(2,2,4)
plt.hist(arvores.Volume)
#(X,X,X) X1 LINHA | X2 COLUNA | X3 POSIÇÃO mantenho o número de linha e coluna

"""#Boxplot"""

plt.boxplot(arvores.Volume, vert=False, showfliers=False, notch= True, patch_artist=True) 
plt.title("Arvores")
plt.xlabel("Volume")

"""Base de dados com tres dados"""

plt.boxplot(arvores)
plt.title("Arvores")
plt.xlabel("Dados")

plt.boxplot(arvores.Volume, vert=False)
plt.boxplot(arvores.Volume, vert=False)
plt.boxplot(arvores.Girth, vert=False)
plt.boxplot(arvores.Height, vert=False)
plt.title("Arvores")
plt.xlabel("Dados")